runtime: nodejs18

handlers:
- url: /dist/(.*\.(html|css|js|json|svg))$
  static_files: dist/\1
  upload: dist/(.*\.(html|css|js|json|svg))$

- url: /assets/(.*\.css)$
  static_files: dist/assets/\1
  upload: dist/assets/(.*\.css)$
  mime_type: text/css

- url: /assets/(.*\.js)$
  static_files: dist/assets/\1
  upload: dist/assets/(.*\.js)$
  mime_type: application/javascript

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html

